# Generated by Django 6.1.1 on 2026-09-25 08:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('SALES_ENG', 'Sales Engineer'), ('PROJ_ENG_SALES', 'Project Engineer (Sales)'), ('DESIGN_ENG_SALES', 'Design Engineer (Sales)'), ('PROJ_ENG_PROD', 'Project Engineer (Production)'), ('DESIGN_ENG_PROD', 'Design Engineer (Production)'), ('PROD_MANAGER', 'Production Manager'), ('SUPPLY_CHAIN', 'Supply Chain'), ('STORES', 'Stores'), ('LOGISTICS', 'Logistics'), ('PROD_TEAM', 'Production Team'), ('QC', 'Quality Control'), ('FINANCE', 'Finance'), ('HR', 'Human Resources')], default='SALES_ENG', max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.branch')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('SALES_QUOTATION', 'Sales Quotation'), ('PROFITABILITY', 'Profitability Approval'), ('PURCHASE_ORDER', 'Purchase Order'), ('STOCK_REQUISITION', 'Stock Requisition'), ('MATERIAL_REQUISITION', 'Material Requisition'), ('LEAVE', 'Leave Application'), ('PAYROLL', 'Payroll'), ('SOA_SUBMISSION', 'SOA Submission')], max_length=50)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('required_role', models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('SALES_ENG', 'Sales Engineer'), ('PROJ_ENG_SALES', 'Project Engineer (Sales)'), ('DESIGN_ENG_SALES', 'Design Engineer (Sales)'), ('PROJ_ENG_PROD', 'Project Engineer (Production)'), ('DESIGN_ENG_PROD', 'Design Engineer (Production)'), ('PROD_MANAGER', 'Production Manager'), ('SUPPLY_CHAIN', 'Supply Chain'), ('STORES', 'Stores'), ('LOGISTICS', 'Logistics'), ('PROD_TEAM', 'Production Team'), ('QC', 'Quality Control'), ('FINANCE', 'Finance'), ('HR', 'Human Resources')], max_length=30)),
                ('rank', models.IntegerField(default=1, help_text='Chronological approval rank (1=first)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_to_action', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', 'created_at'],
                'indexes': [models.Index(fields=['module', 'reference_id'], name='core_approv_module_ae031e_idx')],
            },
        ),
    ]
