# Generated by Django 6.1.1 on 2026-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='required_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('SALES_ENG', 'Sales Engineer'), ('PROJ_ENG_SALES', 'Project Engineer (Sales)'), ('DESIGN_ENG_SALES', 'Design Engineer (Sales)'), ('PROJ_ENG_PROD', 'Project Engineer (Production)'), ('DESIGN_ENG_PROD', 'Design Engineer (Production)'), ('PROD_MANAGER', 'Production Manager'), ('SUPPLY_CHAIN', 'Supply Chain'), ('STORES', 'Stores'), ('LOGISTICS', 'Logistics'), ('PROD_TEAM', 'Production Team'), ('QC', 'Quality Control'), ('FINANCE', 'Finance'), ('HR', 'Human Resources'), ('ACCOUNTANT', 'Accountant'), ('ACCOUNTS', 'Accounts')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SALES_ENG', 'Sales Engineer'), ('PROJ_ENG_SALES', 'Project Engineer (Sales)'), ('DESIGN_ENG_SALES', 'Design Engineer (Sales)'), ('PROJ_ENG_PROD', 'Project Engineer (Production)'), ('DESIGN_ENG_PROD', 'Design Engineer (Production)'), ('PROD_MANAGER', 'Production Manager'), ('SUPPLY_CHAIN', 'Supply Chain'), ('STORES', 'Stores'), ('LOGISTICS', 'Logistics'), ('PROD_TEAM', 'Production Team'), ('QC', 'Quality Control'), ('FINANCE', 'Finance'), ('HR', 'Human Resources'), ('ACCOUNTANT', 'Accountant'), ('ACCOUNTS', 'Accounts')], default='SALES_ENG', max_length=30),
        ),
    ]
