# Generated by Django 6.1.1 on 2026-09-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_required_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='line_manager',
            field=models.ForeignKey(blank=True, help_text='Line manager who approves leave and requests', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='core.branch'),
        ),
    ]
