# Generated by Django 6.1.1 on 2026-09-28 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_line_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_manager',
            field=models.ForeignKey(blank=True, help_text='Immediate supervisor / line manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
