# Generated by Django 6.1.1 on 2026-09-25 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('PREPARING', 'Preparing'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='PREPARING', max_length=20)),
                ('proof_of_delivery', models.FileField(blank=True, null=True, upload_to='pod/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='sales.clientpo')),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('journal_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_approved', to=settings.AUTH_USER_MODEL)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sales.clientpo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('manufacturing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.manufacturingorder')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pv_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('payable_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.CharField(max_length=300)),
                ('narration', models.TextField(blank=True)),
                ('bank_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Authorization'), ('AUTHORIZED', 'Authorized'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvs_authorized', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvs_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PVAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_date', models.DateTimeField(auto_now_add=True)),
                ('authorization_level', models.CharField(default='LEVEL_1', max_length=50)),
                ('status', models.CharField(default='APPROVED', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='finance.paymentvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='PVFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('filing_reference', models.CharField(blank=True, max_length=100)),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='finance.paymentvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soa_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='soa/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOASubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_to', models.CharField(max_length=200)),
                ('submission_method', models.CharField(default='EMAIL', max_length=50)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='finance.statementofaccount')),
            ],
        ),
    ]
