# Generated by Django 6.1.1 on 2026-09-25 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingBoQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfg_boq_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after procurement complete')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfg_boqs', to='sales.clientpo')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boqs_locked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mfg_drawings/%Y/%m/')),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfg_drawings', to='sales.clientpo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DESIGN_APPROVAL', 'Design Approval'), ('MFG_BOQ', 'Manufacturing BoQ'), ('STOCK_CHECK', 'Stock Check'), ('MANUFACTURING', 'Manufacturing'), ('TESTING', 'Testing'), ('FINISHING', 'Finishing/Rework'), ('QC', 'QC Verification'), ('AS_BUILT', 'As-Built Documentation'), ('PACKAGING', 'Packaging'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], default='DESIGN_APPROVAL', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('as_built_boq', models.FileField(blank=True, null=True, upload_to='as_built/boq/%Y/%m/')),
                ('as_built_drawings', models.FileField(blank=True, null=True, upload_to='as_built/drawings/%Y/%m/')),
                ('as_built_notes', models.TextField(blank=True)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to='sales.clientpo')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('req_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SUPPLIED', 'Supplied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_reqs', to='production.manufacturingorder')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('supplied_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.materialrequisition')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_list_file', models.FileField(blank=True, null=True, upload_to='packing_lists/%Y/%m/')),
                ('packed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='production.manufacturingorder')),
                ('packed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryBoQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boq_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('preliminary_circuit_design', models.FileField(blank=True, null=True, upload_to='prod_eng/circuits/%Y/%m/')),
                ('ga_layout', models.FileField(blank=True, null=True, upload_to='prod_eng/ga/%Y/%m/')),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_boqs', to='sales.clientpo')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryBoQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.preliminaryboq')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='production.manufacturingorder')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QCTestReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('stage', models.CharField(choices=[('ASSEMBLY', 'Assembly'), ('TESTING', 'Testing'), ('FINISHING', 'Finishing/Rework'), ('FINAL_QC', 'Final QC')], max_length=20)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='qc_reports/%Y/%m/')),
                ('passed', models.BooleanField(default=False)),
                ('findings', models.TextField(blank=True)),
                ('rework_required', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_approved', to=settings.AUTH_USER_MODEL)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_reports', to='production.manufacturingorder')),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_conducted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
