# Generated by Django 6.1.1 on 2026-09-25 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_days_per_year', models.IntegerField(default=20)),
                ('is_paid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExitProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('exit_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('RETIREMENT', 'Retirement')], max_length=20)),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('acceptance_letter', models.FileField(blank=True, null=True, upload_to='exit/acceptance/%Y/%m/')),
                ('clearance_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('ACCEPTED', 'Acceptance Approved'), ('CLEARANCE', 'Clearance in Progress'), ('CLEARED', 'All Cleared'), ('FINAL_SETTLEMENT', 'Final Settlement'), ('CLOSED', 'Closed')], default='INITIATED', max_length=30)),
                ('final_settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_processes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('feedback', models.TextField()),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exit_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hr.exitprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ExitClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('is_cleared', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exit_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='hr.exitprocess')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Supervisor'), ('SUPERVISOR_APPROVED', 'Supervisor Approved'), ('HOD_APPROVED', 'HOD Approved'), ('HR_APPROVED', 'HR Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('supervisor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hod_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_leaves', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_approved', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('file', models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
                ('payroll_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollcycle')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SELF_ASSESSMENT', 'Self-Assessment'), ('SUPERVISOR_REVIEW', 'Supervisor Review'), ('EXECUTIVE_AUTH', 'Executive Authorization'), ('COMPLETED', 'Completed')], default='SELF_ASSESSMENT', max_length=30)),
                ('self_comments', models.TextField(blank=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('executive_comments', models.TextField(blank=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_supervised', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='hr.performancecycle')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('self_rating', models.IntegerField(blank=True, null=True)),
                ('supervisor_rating', models.IntegerField(blank=True, null=True)),
                ('final_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='hr.performancecycle')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
