# Generated by Django 6.1.1 on 2026-09-28 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hod_required',
            field=models.BooleanField(default=False, help_text='HOD approval required based on department policy'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='code',
            field=models.CharField(default='ANNUAL', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='holiday_end_month',
            field=models.IntegerField(blank=True, help_text='Month number when this type stops being available (e.g. 1 for January)', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='holiday_start_month',
            field=models.IntegerField(blank=True, help_text='Month number when this type becomes available (e.g. 12 for December)', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_mandatory_holiday',
            field=models.BooleanField(default=False, help_text='True for the December mandatory holiday period only'),
        ),
    ]
