# Generated by Django 6.1.1 on 2026-09-28 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exitprocess',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exit Process', 'verbose_name_plural': 'Exit Processes'},
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='clearance_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='close_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='exit_documents',
            field=models.FileField(blank=True, null=True, upload_to='exit/documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='final_settlement_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='final_settlement_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_settlements_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exitprocess',
            name='exit_type',
            field=models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('RETIREMENT', 'Retirement'), ('CONTRACT_END', 'Contract End')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exitprocess',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('ACCEPTED', 'Acceptance Approved'), ('CLEARANCE', 'Clearance in Progress'), ('CLEARED', 'All Cleared'), ('FINAL_SETTLEMENT', 'Final Settlement'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30),
        ),
    ]
