# Generated by Django 6.1.1 on 2026-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_exitprocess_options_exitprocess_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exitinterview',
            options={'ordering': ['-interview_date']},
        ),
        migrations.RemoveField(
            model_name='exitinterview',
            name='feedback',
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='benefits_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='could_have_stayed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='growth_opportunities',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='job_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1=Very Dissatisfied, 5=Very Satisfied', null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='leadership_confidence',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Confidence in senior leadership', null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='overall_experience',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='pay_fairness',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Fairness of pay for work performed', null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='reason_for_leaving',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='role_clarity',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Clarity of job responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='supervisor_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Relationship with immediate supervisor', null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='team_collaboration',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Working relationship with colleagues', null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='training_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='what_could_improve',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='what_liked_most',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='work_life_balance',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='would_recommend',
            field=models.BooleanField(blank=True, help_text='Would recommend company as a place to work', null=True),
        ),
    ]
