# Generated by Django 6.1.1 on 2026-09-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='bin_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheets/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturer',
            field=models.CharField(blank=True, default='ABB', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price (optional)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('ABB', 'ABB Products'), ('PUMPS', 'Pumps'), ('VALVES', 'Valves'), ('INSTRUMENTATION', 'Instrumentation'), ('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('SPARES', 'Spare Parts'), ('OTHER', 'Other')], default='ABB', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['part_number'], name='procurement_part_nu_7afdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='procurement_categor_387020_idx'),
        ),
    ]
