# Generated by Django 6.1.1 on 2026-09-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_inventoryitem_bin_number_inventoryitem_datasheet_and_more'),
        ('sales', '0002_clientpoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='carrier',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('FREIGHT_FORWARDER', 'Freight Forwarder'), ('LOCAL_COURIER', 'Local Courier'), ('SUPPLIER', 'Supplier Ships Directly'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='carrier_name',
            field=models.CharField(blank=True, help_text='Specific carrier or forwarder name if not DHL/FedEx/etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping/freight charges (separate from goods)', max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_confirmation_file',
            field=models.FileField(blank=True, null=True, upload_to='po_confirmations/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_confirmation_ref',
            field=models.CharField(blank=True, help_text='Supplier reference from their order confirmation', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sourcing_type',
            field=models.CharField(choices=[('LOCAL', 'Local Supplier'), ('INTERNATIONAL', 'International Supplier'), ('KSB', 'KSB Direct')], default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_freight_forwarder',
            field=models.BooleanField(default=False, help_text='Handles shipping/freight for international orders'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_ksb_partner',
            field=models.BooleanField(default=False, help_text='Direct KSB manufacturer or authorized KSB distributor'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('FREIGHT_FORWARDER', 'Freight Forwarder'), ('SERVICE_PROVIDER', 'Service Provider'), ('OTHER', 'Other')], default='DISTRIBUTOR', max_length=30),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='enquiry',
            field=models.ForeignKey(blank=True, help_text='Linked enquiry (for pre-PO sourcing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_rfqs', to='sales.enquiry'),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='sourcing_type',
            field=models.CharField(choices=[('LOCAL', 'Local Supplier'), ('INTERNATIONAL', 'International Supplier'), ('KSB', 'KSB Direct')], default='LOCAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='client_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='sales.clientpo'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING_PROFITABILITY', 'Pending Profitability Approval'), ('PENDING_FINANCE', 'Pending Finance Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent to Supplier'), ('CONFIRMED', 'Order Confirmed by Supplier'), ('IN_TRANSIT', 'In Transit / Shipping'), ('RECEIVED', 'Goods Received'), ('CANCELLED', 'Cancelled')], default='PENDING_PROFITABILITY', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierrfq',
            name='client_po',
            field=models.ForeignKey(blank=True, help_text='Client PO (required when fulfilling a won project)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rfqs', to='sales.clientpo'),
        ),
    ]
