# Generated by Django 6.1.1 on 2026-09-26 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorder_carrier_purchaseorder_carrier_name_and_more'),
        ('sales', '0002_clientpoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquirySourcing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_checked', models.BooleanField(default=False)),
                ('store_checked_at', models.DateTimeField(blank=True, null=True)),
                ('store_available', models.BooleanField(blank=True, help_text='True=in stock, False=needs sourcing, Null=not checked yet', null=True)),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, help_text='Quantity available in store at check time', max_digits=14)),
                ('store_notes', models.TextField(blank=True)),
                ('sourcing_type', models.CharField(blank=True, choices=[('LOCAL', 'Locally Sourced'), ('INTERNATIONAL', 'International'), ('KSB', 'KSB Direct'), ('IN_STOCK', 'From Store Stock')], max_length=20)),
                ('sourcing_decision_at', models.DateTimeField(blank=True, null=True)),
                ('sourcing_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_CHECK', 'Pending Store Check'), ('IN_STOCK', 'Available in Store'), ('NEEDS_SOURCING', 'Needs Sourcing'), ('SOURCING', 'Sourcing in Progress'), ('OFFER_RECEIVED', 'Offer Received from Supplier'), ('QUOTED', 'Quotation Prepared'), ('SENT_TO_SALES', 'Sent to Sales'), ('CLOSED', 'Closed')], default='PENDING_CHECK', max_length=30)),
                ('quotation_sent_to_sales', models.BooleanField(default=False, help_text='SC prepared quote and forwarded to Sales/EDM')),
                ('quotation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing', to='sales.enquiry')),
                ('handled_by', models.ForeignKey(blank=True, help_text='SC officer assigned to this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_handled', to=settings.AUTH_USER_MODEL)),
                ('sourcing_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_decisions', to=settings.AUTH_USER_MODEL)),
                ('store_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquiry Sourcing',
                'verbose_name_plural': 'Enquiry Sourcing',
                'ordering': ['-created_at'],
            },
        ),
    ]
