# Generated by Django 6.1.1 on 2026-09-26 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_required_role_alter_user_role'),
        ('procurement', '0004_enquirysourcing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('location', models.CharField(blank=True, help_text='Shelf/Rack', max_length=100)),
                ('bin_number', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='procurement.inventoryitem')),
            ],
            options={
                'verbose_name': 'Branch Stock',
                'verbose_name_plural': 'Branch Stocks',
                'ordering': ['item__part_number', 'branch__name'],
                'unique_together': {('item', 'branch')},
            },
        ),
    ]
