# Generated by Django 6.1.1 on 2026-09-26 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_required_role_alter_user_role'),
        ('procurement', '0005_branchstock'),
        ('sales', '0002_clientpoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('req_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('requisition_type', models.CharField(choices=[('INTERNAL', 'Internal (Department)'), ('EXTERNAL', 'External (Client Order)')], max_length=20)),
                ('source_department', models.CharField(blank=True, choices=[('AUTOMATION', 'Automation'), ('SERVICE', 'Service'), ('PRODUCTION', 'Production'), ('PROJECT', 'Project'), ('PROCUREMENT', 'Procurement'), ('OTHER', 'Other')], help_text='Required for INTERNAL requisitions', max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PICKING', 'Picking in Progress'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('waybill_no', models.CharField(blank=True, max_length=30)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_approved', to=settings.AUTH_USER_MODEL)),
                ('client_po', models.ForeignKey(blank=True, help_text='Required for EXTERNAL requisitions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_requests', to='sales.clientpo')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_dispatched', to=settings.AUTH_USER_MODEL)),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_packed', to=settings.AUTH_USER_MODEL)),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_picked', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_received', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_requested', to=settings.AUTH_USER_MODEL)),
                ('requesting_branch', models.ForeignKey(blank=True, help_text='Branch stocking out the items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_from', to='core.branch')),
                ('target_branch', models.ForeignKey(blank=True, help_text='Target branch (if cross-branch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_to', to='core.branch')),
            ],
            options={
                'verbose_name': 'Requisition Request',
                'verbose_name_plural': 'Requisition Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('uom', models.CharField(default='pcs', max_length=20)),
                ('quantity_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_approved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_issued', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('picked', models.BooleanField(default=False)),
                ('packed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.inventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.requisitionrequest')),
            ],
        ),
    ]
