# Generated by Django 6.1.1 on 2026-09-26 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_required_role_alter_user_role'),
        ('procurement', '0006_requisitionrequest_requisitionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('transfer_type', models.CharField(choices=[('STOCK', 'Stock Replenishment'), ('PROJECT', 'Project Requirement')], default='STOCK', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('waybill_no', models.CharField(blank=True, max_length=30)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('received_notes', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_dispatched', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(help_text='Branch sending the stock', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.branch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_branch', models.ForeignKey(help_text='Branch receiving the stock', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.branch')),
            ],
            options={
                'verbose_name': 'Stock Transfer Request',
                'verbose_name_plural': 'Stock Transfer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('uom', models.CharField(default='pcs', max_length=20)),
                ('quantity_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_approved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.inventoryitem')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.stocktransferrequest')),
            ],
        ),
    ]
