# Generated by Django 6.1.1 on 2026-09-26 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_required_role_alter_user_role'),
        ('procurement', '0007_stocktransferrequest_stocktransferitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.CharField(choices=[('SPACE', 'Space Optimization'), ('REPAIRS', 'Send to Repairs'), ('ACCESS', 'Accessibility'), ('CONSOLIDATION', 'Consolidation'), ('OTHER', 'Other')], max_length=20)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('from_bin', models.CharField(blank=True, max_length=50)),
                ('to_bin', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PLANNED', 'Layout Planned'), ('MOVED', 'Physically Moved'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('moved_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_movements', to='core.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_movements', to='procurement.inventoryitem')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_movements_moved', to=settings.AUTH_USER_MODEL)),
                ('planned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_movements_planned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_movements_requested', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_movements_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Movement',
                'verbose_name_plural': 'Internal Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
