# Generated by Django 6.1.1 on 2026-09-26 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_required_role_alter_user_role'),
        ('procurement', '0008_internalmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CannibalizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('parent_serial', models.CharField(blank=True, help_text='Serial number of the specific unit (if tracked)', max_length=100)),
                ('parent_location', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(choices=[('REPAIR', 'Emergency Repair'), ('PROJECT', 'Project Requirement'), ('SALVAGE', 'Salvage Usable Parts'), ('DISPOSAL', 'Pre-Disposal Harvesting'), ('OTHER', 'Other')], max_length=20)),
                ('reason_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cannibalizations_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cannibalizations', to='core.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cannibalizations_completed', to=settings.AUTH_USER_MODEL)),
                ('parent_item', models.ForeignKey(help_text='The equipment being dismantled', on_delete=django.db.models.deletion.PROTECT, related_name='cannibalization_parent', to='procurement.inventoryitem')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cannibalizations_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cannibalizations_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cannibalization Request',
                'verbose_name_plural': 'Cannibalization Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CannibalizationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('uom', models.CharField(default='pcs', max_length=20)),
                ('destination', models.CharField(choices=[('STOCK', 'Return to Stock'), ('REORDER', 'Send to Supply Chain for Reorder'), ('SCRAP', 'Scrap / Dispose')], default='STOCK', max_length=20)),
                ('is_removed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('part_item', models.ForeignKey(blank=True, help_text='Link to inventory item if the part is stocked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cannibalization_parts', to='procurement.inventoryitem')),
                ('cannibalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.cannibalizationrequest')),
            ],
        ),
    ]
