# Generated by Django 6.1.1 on 2026-09-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_cannibalizationrequest_cannibalizationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionrequest',
            name='source_department',
            field=models.CharField(blank=True, choices=[('AUTOMATION', 'Automation'), ('SERVICE', 'Service'), ('PRODUCTION', 'Production'), ('PROJECT', 'Project'), ('PROCUREMENT', 'Procurement'), ('SALES', 'Sales'), ('OTHER', 'Other')], help_text='Required for INTERNAL requisitions', max_length=30),
        ),
    ]
