# Generated by Django 6.1.1 on 2026-09-29 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_line_manager'),
        ('procurement', '0010_alter_requisitionrequest_source_department'),
        ('sales', '0005_salesorder_projectinstallation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='qty_issued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='qty_rejected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='qty_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_items', to='procurement.supplier'),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='procurement.itemcategory')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_category',
            field=models.ForeignKey(blank=True, help_text='Structured category (replaces the flat category field over time)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='procurement.itemcategory'),
        ),
        migrations.CreateModel(
            name='ItemAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_type', models.CharField(choices=[('ALIAS', 'Alias / Common Name'), ('ALTERNATIVE', 'Alternative Item'), ('SUPERSEDES', 'Supersedes (this replaces…)'), ('SUPERSEDED_BY', 'Superseded By (…replaces this)'), ('OEM', 'OEM Equivalent'), ('CUSTOMER_REF', 'Customer Reference')], default='ALIAS', max_length=20)),
                ('value', models.CharField(help_text='Alias / alt part number / superseding part number', max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='procurement.inventoryitem')),
                ('linked_item', models.ForeignKey(blank=True, help_text='Optional: link to the actual alternative/superseding item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_links', to='procurement.inventoryitem')),
            ],
            options={
                'ordering': ['item__part_number', 'alias_type'],
                'unique_together': {('item', 'alias_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('direction', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('INTERNAL', 'Internal Transfer')], max_length=10)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt from Supplier'), ('ISSUE', 'Issue to Requisition'), ('SALE', 'Sale to Client'), ('CLIENT_RETURN', 'Return from Client'), ('SUPPLIER_RETURN', 'Return to Supplier'), ('REJECTION_PURCHASE', 'Rejected on Receipt (back to Supplier)'), ('REJECTION_SALE', 'Rejected by Client (back from Client)'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT', 'Adjustment'), ('CANNIBAL_IN', 'From Cannibalization'), ('CANNIBAL_OUT', 'To Cannibalization')], max_length=30)),
                ('counterparty_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CLIENT', 'Client'), ('INTERNAL', 'Internal / Branch'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Waybill / invoice / GRN no / external ref', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.branch')),
                ('client_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.clientpo')),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='procurement.goodsreceivednote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='procurement.inventoryitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_performed', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['item', 'branch'], name='procurement_item_id_d84442_idx'), models.Index(fields=['movement_type'], name='procurement_movemen_af9402_idx'), models.Index(fields=['direction'], name='procurement_directi_67659d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_part_number', models.CharField(blank=True, max_length=100)),
                ('last_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier for this item')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='procurement.inventoryitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_items', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Item',
                'verbose_name_plural': 'Supplier Items',
                'ordering': ['supplier__name', 'item__part_number'],
                'unique_together': {('supplier', 'item')},
            },
        ),
    ]
