# Generated by Django 6.1.1 on 2026-09-25 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_inventoryitem_bin_number_inventoryitem_datasheet_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPOItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.clientpo')),
                ('item', models.ForeignKey(blank=True, help_text='Optional link to inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.inventoryitem')),
            ],
        ),
    ]
