# Generated by Django 6.1.1 on 2026-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_clientpoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='application',
            field=models.CharField(blank=True, help_text='Where this will be used / application context', max_length=300),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pump_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Pump technical specifications (fluid, flow, head, etc.)'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='requirement_type',
            field=models.CharField(choices=[('PUMP', 'Pump'), ('AUTOMATION', 'Automation'), ('LV', 'Low Voltage (LV)'), ('MV', 'Medium Voltage (MV)'), ('PROJECT', 'Project'), ('OTHER', 'Other')], default='AUTOMATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='description',
            field=models.TextField(help_text='General description of what the client needs'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('TECH_REVIEW', 'Technical Review'), ('UNDER_REVIEW', 'Under Review'), ('QUOTING', 'Quoting'), ('QUOTED', 'Quoted'), ('WON', 'Project Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20),
        ),
    ]
