# Generated by Django 6.1.1 on 2026-09-28 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_enquiry_application_enquiry_client_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Design/Sales Engineer who reviewed this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='technical_review_notes',
            field=models.TextField(blank=True, help_text='Notes from the technical review (clarifications, findings)'),
        ),
    ]
