# Generated by Django 6.1.1 on 2026-09-28 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_enquiry_reviewed_at_enquiry_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('fulfilment_path', models.CharField(choices=[('WAREHOUSE', 'Warehouse / Dispatch Only'), ('FABRICATION', 'Panel Fabrication / Production'), ('INSTALLATION', 'Project / Installation'), ('MIXED', 'Multiple Paths')], default='WAREHOUSE', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_FULFILMENT', 'In Fulfilment'), ('QC_PENDING', 'QC Pending'), ('QC_PASSED', 'QC Passed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('warehouse_dispatched', models.BooleanField(default=False)),
                ('warehouse_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('panel_fabricated', models.BooleanField(default=False)),
                ('panel_fabricated_at', models.DateTimeField(blank=True, null=True)),
                ('installation_completed', models.BooleanField(default=False)),
                ('installation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('qc_passed', models.BooleanField(default=False)),
                ('qc_passed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order', to='sales.clientpo')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=200)),
                ('site_address', models.TextField()),
                ('site_contact', models.CharField(blank=True, max_length=200)),
                ('site_phone', models.CharField(blank=True, max_length=30)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_led', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='sales.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
